package.json
public/data/movies.json
src/api/useGetMovie.js
src/components/Favorites/Favorites.jsx
src/routes/Favorites/Favorites.jsx
yarn.lock

즐겨찾기 페이지에 즐겨찾기 된 영화 목록 출력
movies.json like=true인 데이터들을 받아옴.
- components/Favorites/Favorites.jsx
- 이미지랑 타이틀 출력
헤더에서 검색해서 데이터 요청할 때 쿼리스트링으로 &like=true를 보내주면 즐겨찾기 된 영화 내에서 검색 가능
#11

[#11]feat: add favorite movie data

---

src/components/Header/Header.jsx
src/components/Movies/Card/Card.jsx
src/components/Movies/Modal/index.jsx
src/components/Movies/Modal/modal.scss
src/components/Movies/index.jsx
src/store/modal.jsx

- scss를 호출하지 않아 발생한 이슈 -> scss 호출
- 모달의 즐겨찾기 버튼 클릭 시 modal을 닫지 않도록 수정

fix: Fix the issue of not being able to render modal

---

src/routes/index.jsx

fix: fix home routing

---

src/api/useFetchData.js
src/components/Movies/Card/Card.jsx
src/components/Movies/Modal/index.jsx
src/components/Movies/Modal/modal.scss
src/components/Movies/index.jsx
src/store/modal.jsx

- eslint 로 변경된거랑
- 그라디언트 관련 + 타이틀데이터도 받아오기 위해 모달 쪽 스토어 수정
- 이미지를 img태그가 아닌 백그라운드 이미지 처리했습니다!

modalcss cover - backgroundImage

---

src/assets/svgs/index.js
src/components/Movies/Card/Card.jsx
src/components/Movies/Card/card.scss
src/components/Movies/movies.scss
src/data/movies.json
src/routes/Layout/Layout.jsx

카드 디자인 변경했습니다.
.inner width: 1200px로 넣어두었습니다. (movie.scss) 
공통 파일 안에 넣어야합니다.
단위에 맞게 해주시고 반응형 맞출때 수정 바랍니다.
다음 작업 시 .movie justify-content: center; 제거하겠습니다

fix: change card design

---

.eslintrc.json
src/api/useSearch.js
src/components/Search/SearchForm/SearchForm.jsx
src/data/movies.json

- eslint 설정 수정
- useSearch 훅으로 분리
- image data 깨진 것 삭제

useSearch sep

---

src/components/Modal/index.jsx
src/components/Modal/modal.scss
src/components/Movies/Card/Card.jsx
src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/ModalContent/modalContent.scss
src/components/Movies/index.jsx
src/routes/Home/Home.jsx
src/store/modal.js

- modal context api의 확장자명을 jsx에서 js로 수정
- modal의 내용물을 렌더하는 ModalContent 컴포넌트 생성
- 영화 게시물 modal을 렌더하는 곳을 home 페이지에서 게시물 리스트인 movies로 이동

polish: modal 관련 작업 처리

---

src/components/Header/TopButton.jsx
src/components/Header/topButton.scss
src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/ModalContent/modalContent.scss
src/routes/Layout/Layout.jsx
src/routes/Routes.module.scss

- 모달 css fix
- 레이아웃 css
- top으로 가는 top버튼(기능만)
- 모달 데이터 가변에 따른 초기데이터 논의 필요..!
- 영화 설명문인 시놉시스랑 서머리(이거두개는 같은 데이터라 괜찬)
- 거의 종이 한장짜리일때가 있고
- 20자쯤 짧을때가 있고
- 아예 없을때가 있습니다.
- 현재 플렉스 + 부분 스크롤을 적용해놓았는데 초기텍스트를 지정할지 여부
- 아니면 모양을 어느정도 희생하여 고정값을 주고 텍스트를 낮게 잡을지
- 아니면 텍스트를 그냥 보여주지 않을지 정해야 할것 같습니다!

fix:top-button / modalCssFix

---

src/components/Portal.jsx

- modal을 렌더링 시킬 dom node를 props로 전달받아 처리하게끔 수정
- dom node의 default값을 document.body로 설정

refactor: Modify so that the portal can receive the dom node where the modal is to be inserted as props.

---

src/components/Header/header.scss
src/components/Modal/modal.scss
src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/ModalContent/modalContent.scss
src/components/Movies/movies.scss

- 모달 css fix(자고 일어나서하니까 왠지 되네여...)
- 헤더를 fixed display로 수정(searchForm 쪽은 작업하고계실것 같아 아직 스로틀 적용은 하지 않았습니다)
- 그치만 무비데이터에 대해서 여전히 얘기할 필요는 있음...!
- 주말 아침 주무실것 같아 이따 everyone으로 바꾸겠습니다:)
header.scss
movies.scss
modalcontent.scss

fix:header / modal css

---

package-lock.json
src/assets/svgs/close.svg
src/assets/svgs/star_filled.svg
src/components/Header/Header.jsx
src/components/Header/TopButton.jsx
src/components/Header/topButton.scss
src/components/Movies/Card/Card.jsx
src/components/Movies/Card/card.scss
src/components/Movies/ModalContent/ModalContent.jsx

- TopButton.jsx → 탑버튼 svg import 및 적용
- topButton.scss → 탑버튼을 최상단으로 올리고, width및 height 100%로 잡힌걸 버튼크기와 동일하게 수정.
- Card.jsx→ 즐겨찾기 빈별 svg파일 import 및 적용
- 빈별에 onClick이벤트로 꽉찬 별로 컴포넌트 변경    
**별 클릭시 카드 모달 활성화되는 부분 수정 필요    
- card.scss → 별 svg 사이즈 수정
- Header.jsx → 로고 클릭시 홈으로 이동
- ModalContent.jsx → close ,빈 별 svg import 및 적용
- 즐겨찾기 버튼 클릭시 별 컴포넌트 변경
- close.svg 사이즈 수정

style svg 삽입 및 css수정

---

src/api/useUpdateFavorite.js
src/components/Movies/Card/Card.jsx

하나의 데이터만 변경하도록 patch로 변경
useUpdateFavorite 안에 put을 patch로 수정

[#39] fix: change favorite api axios (put -> patch)

---

src/components/Header/Header.jsx
src/components/Header/header.scss
src/components/Header/topButton.scss
src/components/Movies/Card/card.scss
src/components/Movies/movies.scss
src/routes/Routes.module.scss
src/styles/mixins/_responsive.scss

- 반응형 웹 적용(임시로 header의 서치바를 모바일 크기에서는 없앴습니다:) 
- 아직 검색기능 작업중이시기에 최대한 scss만 건드렸어여!
- 갤럭시폴드 / 갤럭시 8+ 스크린에 대응하기 위해 responsive 전역변수 값을 약간 수정했습니다.
- 카드가 모바일에선 1개씩, 타블렛에선 2개씩, 데스크탑에서는 4개씩 보이도록 수정했습니다.
(다만 노트북에서 어떻게 보일지 데이터가 없어서... 이부분 맥북에서 확인 부탁드려여ㅜㅜ)
확인하시고 머지 부탁드립니다!
header.jsx
header.scss
topButton.scss
card.scss
movies.scss
Routes.module.scss
_responsive.scss

layout:responsiveSettingChange

---

src/components/Movies/Card/card.scss

- 반응형 웹 수정!
- 폴드(200px...)에서만 1개, 그 이후(모바일)부터 2개
- 타블렛 세로일때 3개, 가로일때 4개
- 데스크탑 4개
로 좀더 세분화해봤습니다 :)
확인하시고 머지 부탁드립니다!
card.scss

fix:responsiveCardDisplay

---

src/components/Favorites/Favorites.jsx
src/components/Movies/Card/card.scss

- 모바일 / 타블렛에서 카드가 1줄 이하일때 찌그러지는 문제 수정
- 즐겨찾기 페이지에 modal component 임시로 import해둠!

fix:css / modal import

---

src/components/Movies/Card/card.scss

각 반응형에서 약간만 더 자연스럽게 넓게 보이게...! 각도를 맞추었습니다:)

fix: contents css fix

---

src/api/config.js
src/api/useGetMovie.js
src/api/useSearch.js
src/api/useSortMovie.js
src/api/useUpdateFavorite.js
src/components/Movies/MovieSort/MovieSort.jsx
src/components/Movies/MovieSort/movieSort.scss
src/components/Movies/index.jsx
src/components/Movies/movies.scss

feat: sort css

---

src/components/Movies/Card/Card.jsx
src/components/Movies/index.jsx
src/components/Search/Dropdown/Dropdown.jsx
src/components/Search/Dropdown/DropdownItems.jsx
src/components/Search/SearchForm/SearchForm.jsx
src/store/search.js

store/search.js에 movieData 삭제
store/movies.js에서 movieData 사용

fix: remove search.js movieData

---

src/components/Favorites/Favorites.jsx

즐겨찾기 페이지 상단 여백추가
components/Favorite.jsx에
movie_wrap추가 - Movies/index.jsx와 동일

fix: add favorite page

---

src/api/useGetMovie.js
src/components/Favorites/Favorites.jsx
src/store/movies.js

즐겨찾기 페이지가 재렌더링 되지 않는 이슈를 recoil의 selector을 이용해 해결하였다.
close #61

fix: Fix Favorites Page Re-rendering Error

---

src/components/Movies/MovieSort/MovieSort.jsx
src/components/Movies/index.jsx
src/hooks/useInfiniteData.js
src/hooks/useObserver.js
src/store/movies.js

- 무한스크롤 리스트와 필터에 적용
- 리코일 스토어 수정!
- MovieSort.jsx
- index.jsx(movie)
- movies.js

feat:infiniteScroll

---

package.json
src/components/Favorites/Favorites.jsx
src/components/Header/Header.jsx
src/components/Header/topButton.scss
src/components/Movies/Card/card.scss
src/components/Movies/index.jsx
src/components/Movies/movies.scss
src/components/Search/Dropdown/dropdown.scss
src/components/Search/SearchForm/SearchForm.jsx
src/data/movies.json
src/hooks/useInfiniteData.js
yarn.lock

- SearchForm → 검색 버튼 엔터 아닌 클릭시 활성화( onClick 추가 )
- 검색시 window.history.pushState('', debouncedKeyword, `/?q=${debouncedKeyword}`); 로 페이지 이동 없이 url에 검색 값만 담기
- input에 autoFocus추가
- Header → 로고 클릭시 url /로 이동 및 데이터 초기화
- 로고 클릭시 home으로 이동 및 useGetAllMovies 재호출 → 검색창 초기화
- css파일 불필요한 주석 제거

feat 로고 onClick 이벤트 적용 및 검색시 url 변경

---

src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/ModalContent/modalContent.scss
src/components/Movies/MovieSort/MovieSort.jsx
src/store/movies.js

- 모달에서 보여줄 영화 정보를 얻는 방식을 selectorFamily를 이용하게끔 리펙토링
- movieSort 컴포넌트의 옵션 key 네이밍 수정

refactor: Implemented to use selectorFamily to obtain the movie information to be displayed in the modal

---

src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/ModalContent/modalContent.scss

모달 더보기 버튼 생성
- ModalContent 버튼 추가
- modalContent.scss 작업
- 임의의 글자수(135자로 지정) 이상 일 경우에만 버튼 나타나도록 처리
open 클래스가 들어갈 경우 높이 값 변경, overflow: scroll

[#69, #74] feat: add modal more button, limit text 

---

src/components/Favorites/Favorites.jsx
src/components/Modal/index.jsx
src/components/Modal/modal.scss
src/components/Movies/Card/Card.jsx
src/components/Movies/ModalContent/ModalContent.jsx
src/components/Movies/index.jsx
src/index.js
src/routes/index.jsx
src/store/modal.js

- modal 전역 상태관리를 context api에서 recoil로 마이그레이션하였다.
- 전역 처리 로직을 ui와 함께 정의

refactor: Migrate modal global state management from context api to recoil

---

README.md

[#77] documentation: update reademe

---

src/components/Card/Card.jsx
src/components/Card/card.scss
src/components/Favorites/Favorites.jsx
src/components/ModalContent/ModalContent.jsx
src/components/ModalContent/modalContent.scss
src/components/Movies/index.jsx

게시물 컴포넌트를 Movies의 하위 폴더가 아닌 components의 최상단으로 이동시켰다.
close #85

refactor: Move to the top of the post component components

---

src/components/Header/Header.jsx
src/components/Movies/MovieSort/MovieSort.jsx
src/components/Movies/index.jsx
src/components/Search/SearchForm/SearchForm.jsx
src/hooks/useInfiniteData.js

- sortData 전체보기에 column 값 부여(렌더링을 위해)
- 검색결과 클리어 추가
- movie/index.jsx
- useInfiniteData
- movieSort.jsx
- store/movie.js
- header.jsx

fix: sort/datafix
